export const ASSSETS = {
  LINKED_LOGO: "/linked_logo.svg",
  GITHUB_LOGO: "/github_logo.svg",
  AVATAR: "/avatar.svg",
  CSS_LOGO: "/css-logo.svg",
  HTML_LOGO: "/html-logo.svg",
  JS_LOGO: "/javascript-logo.svg",
  REACT_LOGO: "/react-logo.svg",
  NEXT_LOGO: "/nextjs-logo.svg",
  TAILWIND_LOGO: "/tailwind-logo.svg",
  TYPESCRIPT_LOGO: "/typescript-logo.svg",
  MUI_LOGO: "/mui-logo.svg",
  SHADCNUI_LOGO: "/shadcnui-logo.svg",
  FIGMA_LOGO: "/figma-logo.svg",
  HCMUTE_LOGO: "/hcmute-logo.png",
  TARGET_ICON: "/target_icon.png",
  HOBBIES_ICON: "/hobbies-icon.png",
  PROJECT_HDMOVIE: "/project-hdmovie.png",
  PROJECT_AMIRAH: "/project-amirah.png",
  PROJECT_EPAPER: "/project-epaper.png",
  ROSHIVN_LOGO: "/roshivn.svg",
  FREELANCE_LOGO: "/freelance.png",
  EXPRESSJS_LOGO: "/expressJS.svg",
  MYSQL_LOGO: "/mysql.svg",
  DOCKER_LOGO: "/docker.svg",
};
